## Обработка ошибок HTTP запросов

Допустим, мы не можем гарантировать, что URL, на который отправляется запрос, является правильным. Допустим, этот URL вводит пользователь.

```html
<body>
  <input value="https://todoappexamplejs.herokuapp.com/items.json" />
  <button>Отправить запрос!</button>
</body>
```

```js
document.querySelector("button").addEventListener("click", function () {
  const request = new XMLHttpRequest();
  request.open("GET", document.querySelector("input").value);

  request.onload = function () {
    console.log(request.responseText);
  };

  request.send();
});
```

Простая версия запроса:

```js
const request = new XMLHttpRequest();
request.open("GET", "https://todoappexamplejs.herokuapp.com/items.json");

request.onload = function () {
  console.log(request.responseText);
};

request.send();
```

Добавим обработку ошибок:

```js
const request = new XMLHttpRequest();
request.open("GET", "https://todoappexamplejs.herokuapp.com/items.json");

request.onload = function () {
  if (request.status == 200) {
    console.log(request.response);
  } else {
    const error = new Error(request.statusText);
    error.code = request.status;
    console.error(error);
  }
};

request.onerror = function () {
  console.error(new Error("Network Error"));
};

request.send();
```

Тот же пример, но уже с fetch:

```js
fetch("https://todoappexamplejs.herokuapp.com/items.json")
  .then((response) => {
    if (!response.ok) {
      throw new Error("Network response was not ok");
    }
    return response.json();
  })
  .then((json) => console.log(json))
  .catch((error) => {
    console.error("A problem with your fetch operation:", error);
  });
```

Полный пример getData с обработкой ошибок

```js
function getData(url) {
  return new Promise(function (resolve, reject) {
    const request = new XMLHttpRequest();
    request.open("GET", url);

    request.onload = function () {
      if (request.status == 200) {
        resolve(request.response);
      } else {
        const error = new Error(request.statusText);
        error.code = request.status;
        reject(error);
      }
    };

    request.onerror = function () {
      reject(new Error("Network Error"));
    };

    request.send();
  });
}

getData("https://todoappexamplejs.herokuapp.com/items.json").then(
  (response) => console.log(response),
  (error) => console.log("Error happened " + error)
);
getData("https://todoappexamplejs.herokuapp.com/items.json")
  .then((response) => console.log(response))
  .catch((error) => console.log("Error happened " + error));
```

#### Задание

Создать функцию request, которая вызывает fetch с урлом \
https://todoappexamplejs.herokuapp.com/items.json \
Функция возвращает результат вызова fetch, т.е. promise \
Работает так:

```js
request().then(response => response.json()).then(data => console.log(data)) \

function request() {
  return fetch('https://todoappexamplejs.herokuapp.com/items.json')
}
request().then(response => response.json()).then(data => console.log(data))
```
